### PR TITLE
Added workflow for Git PR

### PR DESCRIPTION
**Pull request by didaquis**
I have done a manual on how to make a PR in a clean way. 

**It's responsibility of each user to understand the commands suggested in this workflow.**

### CODE REVIEW

**Comment by VGamezz19** [comment]
So powerful ! 👍 but better with MarkDown format. If @manuelbarzi merge it, I will do a refactor in `.MD` in a new PR

**Comment by didaquis** [comment]
OK.
When you do the refactor try not to remove the warnings that are in some commands.

**Comment by manuelbarzi** [comment]
WOW interesting... instead of a plain text README.md, a styled HTML format for this doc )

**Comment by manuelbarzi** [comment]
:) 👍

**Comment by manuelbarzi** [comment]
ALERT! moved file to skylab-bootcamp-201801/staff/didaquis/git/Git - workflow para hacer PR.html

**Pull request merged**
